package com.leadsquared.hr.knowledge.model;

import java.util.List;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * An escalation handed from the bot to a human.
 *
 * <p>Field names are the wire contract with {@code lib/hr-store.ts} — the chat
 * window and the admin dashboard both read every one of them, so they are not
 * free to rename. {@code status}, {@code priority} and {@code route} are stored
 * as the exact strings the frontend uses ({@code in-progress}, {@code hr_ops})
 * rather than enums, so no mapping layer can drift out of sync; {@link
 * com.leadsquared.hr.knowledge.tickets.TicketService} validates them on write.
 *
 * <p>The id is generated by the client so the employee sees a ticket number the
 * instant they escalate, without waiting for a round trip. The server treats a
 * duplicate id as a conflict rather than overwriting.
 *
 * @param createdAt ISO-8601 instant; the dashboard sorts on it lexicographically
 * @param confidence what the NLU scored the query before giving up — kept for
 *     triage and for tuning the thresholds
 * @param transcript the last few turns, so HR reads a conversation and not one
 *     orphaned line
 * @param confidential set for sensitive matters; the dashboard withholds the
 *     employee's identity when it is true
 * @param comments the thread between HR and the employee, oldest first. Null on
 *     documents written before threads existed, so every reader goes through {@link
 *     #thread()} rather than dereferencing it.
 */
@Document(collection = "tickets")
public record Ticket(
    @Id String id,
    String query,
    String reason,
    String raisedBy,
    String raisedByName,
    @Indexed String createdAt,
    @Indexed String status,
    String priority,
    String route,
    String assignee,
    List<String> tags,
    double confidence,
    List<TranscriptTurn> transcript,
    boolean confidential,
    String channel,
    List<TicketComment> comments) {

  /** Never null, so callers and templates do not each need their own guard. */
  public List<TicketComment> thread() {
    return comments == null ? List.of() : comments;
  }

  public Ticket withStatus(String next) {
    return new Ticket(
        id, query, reason, raisedBy, raisedByName, createdAt, next, priority, route, assignee,
        tags, confidence, transcript, confidential, channel, comments);
  }

  public Ticket withComments(List<TicketComment> next) {
    return new Ticket(
        id, query, reason, raisedBy, raisedByName, createdAt, status, priority, route, assignee,
        tags, confidence, transcript, confidential, channel, next);
  }

  /** Whether this address raised the ticket. Case-insensitive; false for a null. */
  public boolean isOwnedBy(String email) {
    return email != null && raisedBy != null && raisedBy.equalsIgnoreCase(email);
  }
}
